export const PRODUCT_ADD = "PRODUCT_ADD"; 
export const PRODUCT_RECEIVED = "PRODUCT_RECEIVED";
export const PRODUCT_SET_QUANTITY = "PRODUCT_SET_QUANTITY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";