export const PRODUCT_RECEIVED = "PRODUCT_RECEIVED";

export const PRODUCT_SET_QUANTITY = "PRODUCT_SET_QUANTITY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_ADD = "PRODUCT_ADD";

export const CHANGE_CATEGORY_MODAL = "CHANGE_CATEGORY_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";
export const REMOVE_MODAL = "REMOVE_MODAL";